# Generated by Django 4.2.7 on 2023-12-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0010_alter_historicalpqrinformacion_usuario_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpqrinformacion',
            name='peticion_pqr_id',
        ),
        migrations.RemoveField(
            model_name='historicalpqrrespuesta',
            name='peticion_pqr_id',
        ),
        migrations.RemoveField(
            model_name='pqrinformacion',
            name='peticion_pqr_id',
        ),
        migrations.RemoveField(
            model_name='pqrrespuesta',
            name='peticion_pqr_id',
        ),
        migrations.AddField(
            model_name='historicalpqrinformacion',
            name='peticion',
            field=models.CharField(max_length=30, null=True, verbose_name='Tipo peticion'),
        ),
        migrations.AddField(
            model_name='pqrinformacion',
            name='peticion',
            field=models.CharField(max_length=30, null=True, verbose_name='Tipo peticion'),
        ),
        migrations.DeleteModel(
            name='HistoricalPqrPeticion',
        ),
        migrations.DeleteModel(
            name='PqrPeticion',
        ),
    ]
