# Generated by Django 4.2.7 on 2023-12-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0010_alter_historicalpqrinformacion_usuario_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpqrinformacion',
            name='num_radicado',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Número de Radicado'),
        ),
        migrations.AlterField(
            model_name='pqrinformacion',
            name='num_radicado',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Número de Radicado'),
        ),
    ]
