# Generated by Django 4.2.7 on 2023-12-14 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0011_alter_historicalpqrinformacion_num_radicado_and_more'),
        ('pqrs', '0012_alter_archivospqrinformacion_codigo_and_more'),
    ]

    operations = [
    ]
